version: '2'
services:
  db:
    image: postgres
  api:
    build: ./api
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./server:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
  ui:
    build: ./ui-web-client
